---
title: "SCtransform integration for Seurat Analysis"
author: "Javier Perales-Patón - javier.perales@bioquant.uni-heidelberg.de - ORCID:0000-0003-0780-6683"
output: 
  github_document:
    html_preview: false
params:
  ID: 
    value: x
  OUTDIR:
    value: x
---

```{r, include=FALSE}
# params <- list(ID="LDvsTN", OUTDIR="./02_SCTintegration")
```

## Environment
### set env
```{r env}
options(stringsAsFactors = FALSE)
# Seed number
set.seed(1234)

# Input directory
INPUT_DIR <- "./01_Seurat/";
INPUT_TAG <- "_Seurat" # Tag generated by prev step

# Output directory
OUTDIR <- params$OUTDIR
if(!dir.exists(OUTDIR)) dir.create(OUTDIR);

# Figures
FIGDIR <- paste0(OUTDIR, "/figures/")
knitr::opts_chunk$set(fig.path=FIGDIR)
knitr::opts_chunk$set(dev=c('png'))
# Data
DATADIR <- paste0(OUTDIR, "/data/")
if(!dir.exists(DATADIR)) dir.create(DATADIR);
```


```{r libs}
library(Seurat)
source("../src/seurat_fx.R")

# src: https://stackoverflow.com/questions/40536067/how-to-adjust-future-global-maxsize-in-r
# 6 globals that need to be exported for the future expression (‘FUN()’) is 2.54 GiB
# This exceeds the maximum allowed size of 500.00 MiB
options(future.globals.maxSize= (1024*3)*1024^2)
```

## Load data
```{r read_idx}
yaml_fl <- paste0("../index/contrasts/",params$ID,".yaml")
stopifnot(file.exists(yaml_fl))
# Find index file
idx <- yaml::read_yaml(yaml_fl)
# Get groups
GRx_idx <- setNames(vector("list", length(idx$groups)),
		    idx$groups)
for(gr in idx$groups) {
	yaml_fl <- paste0("../index/groups/",gr,".yaml")
	stopifnot(file.exists(yaml_fl))
	GRx_idx[[gr]] <- yaml::read_yaml(yaml_fl)$samples
}
# Get for samples
sampleFLs <- vector("character", length=length(unlist(GRx_idx)))
names(sampleFLs) <- unlist(GRx_idx)
for(sampleID in unlist(GRx_idx)) {
	S_rds <- paste0(INPUT_DIR,"/",sampleID,INPUT_TAG,"/data/S.rds")
# 	stopifnot(file.exists(S_rds))
	sampleFLs[sampleID] <- ifelse(file.exists(S_rds), S_rds, NA)
}
# Sanity check in detail for individual samples for the contrast
if(any(is.na(sampleFLs))) {
	cat("[ERROR] : Certain samples that belong to any of the groups do not have Seurat objects:\n", file=stderr())
	cat(paste0("[ERROR] : DO exist:", paste0(na.omit(sampleFLs), collapse=", "), "\n"), file=stderr())
	cat(paste0("[ERROR] : do NOT exist:", paste0(sampleFLs[is.na(sampleFLs)], collapse=", "), "\n"), file=stderr())
	stop("Please, generate the samples that do NOT exist and revise indexes for groups and contrasts.\n")
}
```

```{r load_seurats}
# Create list of seurat objects
SL <- setNames(vector("list", length=length(sampleFLs)), 
	       names(sampleFLs))
# For every sample, add it to the list
for(sname in names(sampleFLs)) {
	sname_fl <- sampleFLs[sname]
	cat(paste0("[INFO] loading SeuratObject for ",sname,"\n"),file=stdout())
	S <- readRDS(sname_fl)
	cat(paste0("[INFO] Add ",sname," to list of SeuratObjects\n"),file=stdout())
	SL[[sname]] <- S
	rm(S)
}
```

```{r integration, warning=FALSE}
features <- SelectIntegrationFeatures(object.list = SL, nfeatures = 3000)
SL <- PrepSCTIntegration(object.list = SL, anchor.features = features, verbose = FALSE)

anchors <- FindIntegrationAnchors(object.list = SL, normalization.method = "SCT", anchor.features=features, verbose=FALSE)
S <- IntegrateData(anchorset = anchors, normalization.method = "SCT", verbose = FALSE)
rm(SL)
```

We apply high dimensionality reduction methods and unsupervised clustering
```{r norm_hdr}
DefaultAssay(S) <- "integrated"

S <- ScaleData(S, verbose=FALSE)
S <- RunPCA(S, npcs=50, verbose= FALSE)
calcNPCs <- get_npcs(S)
(nPCs <- calcNPCs$npcs)
ElbowPlot(S, ndims=50) + geom_vline(xintercept = nPCs)

S <- RunUMAP(S, reduction = "pca", dims = 1:nPCs)
```

```{r umap_plot}
DimPlot(S, reduction="umap")
```

## Save the Seurat Object
```{r save}
saveRDS(S, paste0(OUTDIR,"/S.rds"))
```

## SessionInfo
```{r}
sessionInfo()

{                                                                                                                                                                                                           
sink(file=paste0(OUTDIR,"/sessionInfo.txt"))
print(sessionInfo())
sink()
}
```

